### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by shhlkien** [shhlkien/just-forget-it#1]
- [ ] clean domain manually
- [ ] cleanup on leave
- [ ] help, wiki page
- [ ] snooze
